const types = {
    CREATE_CHANNEL: "CREATE_CHANNEL",
    CHANGE_CHANNEL: "CHANGE_CHANNEL",
    UPDATE_CHANNEL: "UPDATE_CHANNEL",
    REMOVE_CHANNEL: "REMOVE_CHANNEL",
    DELETE_CHANNEL: "DELETE_CHANNEL",
    CHANNEL_JOINED: "CHANNEL_JOINED"
}
export default types