const types = {
    CREATE_LISTENER: "CREATE_LISTENER",
    CHANGE_LISTENER: "CHANGE_LISTENER",
    UPDATE_LISTENER: "UPDATE_LISTENER",
    REMOVE_LISTENER: "REMOVE_LISTENER",
    DELETE_LISTENER: "DELETE_LISTENER",
}
export default types