const types = {
    CREATE_PROJECT: 'CREATE_PROJECT',
    CHANGE_PROJECT: 'CHANGE_PROJECT',
    UPDATE_PROJECT: 'UPDATE_PROJECT',
    REMOVE_PROJECT: 'REMOVE_PROJECT',
    PROJECT_CONNECTED: 'PROJECT_CONNECTED',
    START: 'START',
    IMPORT_REDUX: 'IMPORT_REDUX',
}
export default types