const types = {
    CONNNECT_SOCKET: "CONNNECT_SOCKET",
    JOIN_CHANNEL: "JOIN_CHANNEL",
    SEND_PUSH: "SEND_PUSH",
    LISTEN_EVENT: "LISTEN_EVENT",
    RELISTEN_EVENT: "RELISTEN_EVENT",
    UNLISTEN_EVENT: "UNLISTEN_EVENT",
    UNSUBSCRIBE_LISTENER: "UNSUBSCRIBE_LISTENER",
}
export default types